### ISSUE TITLE
Hold shift when dragging to lock movement on the x or y axis

### ISSUE THREAD

**Issue by haydn** [haydn/sketchbook-js#3]

**Comment by Mxchaeltrxn** [comment]
Would be happy to do this as well. 

I'm not quite sure how to implement it though. I've thought about locking mouse movement along one axis but I'm not sure how that's implemented. 

I also thought about locking the component position along the desired axis but I'm not sure what happens when the user releases `shift` and still has their mouse down. I imagine the component would teleport to the mouse if it moved.

**Comment by haydn** [comment]
@Mxchaeltrxn Sweet! I recommend holding off doing too much until #36 gets merge because you're going to want to modify some of the same code that's been touched in that PR.

> I also thought about locking the component position along the desired axis but I'm not sure what happens when the user releases shift and still has their mouse down. I imagine the component would teleport to the mouse if it moved.

I think this is the approach you should take. If you play around with Figma (free to sign-up and use), you can get a feel for how this typically works in a design app — which is exactly as you've described.
