### ISSUE TITLE
Double clicking a layer in layers panel to edit name

### ISSUE THREAD

**Issue by haydn** [haydn/sketchbook-js#9]

**Comment by Mxchaeltrxn** [comment]
I'd like to do this. 

Some questions:
If a few layers are already selected and I double click on an already selected layer, what should the expected behaviour be? I'm thinking everything goes unselected and the user is able to edit the layer they clicked on.

As for the actual editing feature, what seems most feasible to me is updating the li element to be contentEditable and updating state onBlur. It won't update the state immediately but I don't think that's a big deal, considering the only alternative I can think of is using react-contenteditable or turning the list elements into input elements.

**Comment by haydn** [comment]
> If a few layers are already selected and I double click on an already selected layer, what should the expected behaviour be? I'm thinking everything goes unselected and the user is able to edit the layer they clicked on.

Yeah, this sounds right to me. In fact I reckon without any effort on our part the first click will automatically cause just one layer to be selected.

> As for the actual editing feature, what seems most feasible to me is updating the li element to be contentEditable and updating state onBlur. It won't update the state immediately but I don't think that's a big deal, considering the only alternative I can think of is using react-contenteditable or turning the list elements into input elements.

I think you'll need to avoid using `contentEditable` — it lets the user enter rich text with all sorts of whacky formatting that'll make life hard. Switching the text with a `<input type="text" onChange={/*...*/} value={layer.name} />` is probably the most straight forward setup.
